In [4]:
import torch
ss = [2,4,3]
a = [torch.arange(0, s) for s in ss]
print(a)
print(type(a))

[tensor([0, 1]), tensor([0, 1, 2, 3]), tensor([0, 1, 2])]
<class 'list'>


In [9]:
 # 假设是时间步T1
T1 = torch.tensor([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
 # 假设是时间步T2
T2 = torch.tensor([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90]])

a = torch.stack((T1,T2),dim=0)
# a = torch.stack((T1,T2)) # 不写第二个参数的话，默认是0
print(a)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 20, 30],
         [40, 50, 60],
         [70, 80, 90]]])


In [11]:
size = (32,32,16)
vectors = [torch.arange(0, s) for s in size]
grids = torch.meshgrid(vectors)
grid = torch.stack(grids)
grid = torch.unsqueeze(grid, 0) # 增加一个维度 
grid = grid.type(torch.FloatTensor)
print(grid.size())

torch.Size([1, 3, 32, 32, 16])


In [12]:
import torch
import torch.nn.functional as F

# 假设你的预测结果和目标标签是两个五维的张量
predictions = torch.randn(2,2)
targets = torch.randn(2,2)

print(predictions)
print(targets)
# # 使用均方误差损失计算损失
# loss = F.mse_loss(predictions, targets)

# 或者使用均方误差损失类
loss_fn = torch.nn.MSELoss()
loss = loss_fn(predictions, targets)

# 打印损失值
print("Loss:", loss.item())


tensor([[ 0.5722,  0.3477],
        [-0.0857,  2.4341]])
tensor([[-0.2455, -1.7906],
        [ 0.7803, -1.0738]])
Loss: 4.574143409729004


In [ ]:
import os
file = '/media/user_gou/Elements/Shi/Attention-Reg-macos/draft/SPT.py'
dir = os.path.dirname(file)
print(dir)


